// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD2hiDLs28rlF87KrQSbg_E4_E8fAIzOw',
    appId: '1:753918786589:android:401c824d6602af546f1af4',
    messagingSenderId: '753918786589',
    projectId: 'dzen-chat-384f9',
    storageBucket: 'dzen-chat-384f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4NunmyfL9-aW90YCq0hep9VEaIogZmIk',
    appId: '1:753918786589:ios:08b6bead2e9834886f1af4',
    messagingSenderId: '753918786589',
    projectId: 'dzen-chat-384f9',
    storageBucket: 'dzen-chat-384f9.appspot.com',
    androidClientId: '753918786589-4fubo02fm70s5rvt1io1ocd33pqg54gr.apps.googleusercontent.com',
    iosClientId: '753918786589-gsec7da16vht1agl8ml2jmlbkv1f2v6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.dzenChat',
  );
}
